### ISSUE TITLE
Clean des couleurs (variables + classes)

### ISSUE THREAD

**Issue by Nyxis** [LinkValue/MajoraAdminTheme#2]
Remplacer les classes de couleur "red", "dark-navy" etc... par des libellés génériques : "primary-color", "secondary-color", "lighter-primary-color" etc...

Même chose pour le nom des variables.

**Comment by Yimiprod** [comment]
https://github.com/LinkValue/MajoraAdminTheme/pull/4

**Comment by Yimiprod** [comment]
Il me semble que cette PR à été mergée et validée, je ferme
